### ISSUE TITLE
Posterior predictive covariance and standard deviation

### ISSUE THREAD

**Issue by KrisNguyen135** [chariff/GPro#4]
It seems the calculation of the posterior predictive covariance matrix might be more involved than https://github.com/chariff/GPro/blob/master/GPro/preference.py#L243.

Please see the top right corner of page 4 of [Chu and Ghahramani, 2005](http://mlg.eng.cam.ac.uk/zoubin/papers/icml05chuwei-pl.pdf).

The Λ_MAP (loss Hessian) matrix would need to be computed. The inversion of that matrix might be numerically difficult to do, but it seems with some algebra, we might only need to invert a nicer matrix, according to [this document](http://www2.imm.dtu.dk/pubdb/edoc/imm6151.pdf).

I'd be happy to take a stab at this if you'd like.

Thanks,
Quan

**Comment by chariff** [comment]
Another great catch. The loss Hessian is indeed missing in the calculation of the posterior predictive covariance matrix. This is a very intersting matrix identity, thanks for sharing it. Please go ahead and make the changes.

**Comment by KrisNguyen135** [comment]
Fixed in #6. Thanks Chariff.
