### ISSUE TITLE
Problem when using Sensguide API: Application shutting down

### ISSUE THREAD

**Issue by fho177** [chariff/GPro#5]
I have been trying to use your software Sensguide, but the GUI application seems to always shut down when I try to use the "Update" function to generate random values for all features.
I am not sure what could cause this issue, I am using it on 64-bit Windows 10 Intel Core 7@2.6 GHz, 16GB RAM.    
Could you let me know what could cause this problem and how to solve it?

Thank you!

**Comment by chariff** [comment]
There are indeed some minor issues on Windows 10. I am working on a more stable version and will release before the end of the month. Shoot me an email and I will let you know when it is ready.

**Comment by fho177** [comment]
Thank you for your reply, understood.
